export const Enums = {
  MESSAGE: "MESSAGE",
  NOTIFICATION: "NOTIFICATION",
  JOIN: "JOIN",
  LEAVE: "LEAVE",
  DISCONNECT: "DISCONNECT",
  SEND_MESSAGE: "SEND_MESSAGE",
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  SEND_ONLINE_USERS: "SEND_ONLINE_USERS",
};
